name: React CD

on:
  push:
    branches: ['main']

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node 20 설정
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 의존성 설치
        run: npm ci

      - name: Build
        run: npm run build

      - name: FEESH_FRONT CD Discord Notification (success)
        if: ${{ success() }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_FRONT_WEBHOOK }}
          status: ${{ job.status }}
          title: '✅ 성공 ✅'
          description: '배포 성공'
          color: 65280
          username: 'FEESH-FRONT-bot'

      - name: FEESH_FRONT CD Discord Notification (failure)
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_FRONT_WEBHOOK }}
          status: ${{ job.status }}
          title: '❗️ 실패 ❗️'
          description: '배포 실패'
          color: 16711680
          username: 'FEESH-FRONT-bot' 